# Generated by Django 2.1.4 on 2018-12-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(default='xxx', max_length=64),
        ),
        migrations.AddField(
            model_name='job',
            name='role',
            field=models.CharField(default='xxx', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='year',
            field=models.IntegerField(default=2018),
        ),
    ]
